### ISSUE TITLE
Dynamo_Toolkit: Enum value lost

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Dynamo_Toolkit#130]
when I save file with `Discipline `Enum value 
![image](https://user-images.githubusercontent.com/26113670/51607274-2279ff80-1f0c-11e9-9f84-fc5e788323f7.png)

and reopen ...value is lost ... so far only `Discipline ` does not work but I did not tested all 
![image](https://user-images.githubusercontent.com/26113670/51607367-56edbb80-1f0c-11e9-9176-e5e34a025016.png)

**Comment by michaldengusiak** [comment]
same issue with
`TextComparisonType`
![image](https://user-images.githubusercontent.com/26113670/54135841-78e6c300-4412-11e9-9671-2bd6e0ca7cbb.png)

**Comment by adecler** [comment]
@michaldengusiak , do you still have that problem?
I tried both on DynamoSandbox and DynamoRevit and it works fine for me.

**Comment by michaldengusiak** [comment]
@adecler 
correct this is solved now in both Dynamo
![image](https://user-images.githubusercontent.com/26113670/65697717-4bdac480-e073-11e9-8459-48a46ff72f35.png)
