### ISSUE TITLE
Dynamo_Toolkit: Explode Issue

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Dynamo_Toolkit#132]
When we there is list with sublist we need to get first item first so structure is generate and then we can reconnect to original full list. Otherwise this will not work. 

![image](https://user-images.githubusercontent.com/26113670/52208647-411bb700-2879-11e9-9a3c-8f8e32c62d56.png)

and to fix it reconnect to first item 
![image](https://user-images.githubusercontent.com/26113670/52208675-5c86c200-2879-11e9-8a2f-4a2b8e55c991.png)
 and now back to full list
![image](https://user-images.githubusercontent.com/26113670/52208724-80e29e80-2879-11e9-9b67-3327342e76e4.png)

of course it works only on ExpolodeObject (Old)
I added @epignatelli  as this might be BHoM_UI related..

**Comment by epignatelli** [comment]
Sorry guys - not that that confident with the Dynamo API. Let me know if it is a BHoM_UI issue once you identified it is. I can scan through a fix it then.
