### ISSUE TITLE
Dynamo_Toolkit: upgrade to 2.1.0

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Dynamo_Toolkit#139]
I took some time with @ZiolkowskiJakub  to debug my Dynamo, as struggling to get it open with BHoM.
We checked possible upgrade to 2.2 as part of this test.

InPortData was removed from class NodeModel (Dynamo.Graph.Nodes)
so extra work will be needed for upgrade and get this toolkit working

**Comment by michaldengusiak** [comment]
@al-fisher  seems this will be needed for our Topologic workflow and also for Revit 2020 that is in pilot test right now. As discussed lets add this to priority list.

**Comment by pawelbaran** [comment]
@al-fisher @adecler this issue needs to be resolved in order to make Dynamo_Toolkit work with Revit 2020 and above. Maybe worth hitting it up?

**Comment by al-fisher** [comment]
Thanks @pawelbaran - agreed. @adecler - I think this is basically what we discussed this week with priority of Dynamo_Toolkit. Fix bugs - but focus on 2.1.0 for new dev.
Is that right?

Reassigning issue and adding to this milestone for discussion and planning

**Comment by adecler** [comment]
Yes, exactly. I am currently working on closing the pending bug issues on Dynamo to leave it in a decent enough state. But will then move to work on version 2 exclusively.

**Comment by michaldengusiak** [comment]
Great to see this moving on :)
