### ISSUE TITLE
Dynamo_Toolkit: Issue with loosing data

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Dynamo_Toolkit#141]
as we discover during testing this PR https://github.com/BHoM/Revit_Toolkit/pull/303
there is issue with losing data when pushing, this could be affected by other toolkit but I am logging here as starting point

![image](https://user-images.githubusercontent.com/26113670/58971319-1a33aa00-87b3-11e9-88f2-785eb1c6bb3c.png)

**Comment by IsakNaslundBh** [comment]
Think this comes from the fact that the `RevitFilePreview` class contains  `XDoxument`. Would not surprise me if that can not be serialised to Bson currently, which is done as part of sending the packages over the sockets.

You can try this via a simple ToJson and FromJson on the `RevitFilePreview` document as check what you get.

**Comment by ZiolkowskiJakub** [comment]
Hi @IsakNaslundBh,

That is true. My bad. I did not realise that. I will update it on Revit side.
