### ISSUE TITLE
Clearer update instructions needed in "Depreciated" error message.

### ISSUE THREAD

**Issue by JustinZarbBH** [BHoM/Dynamo_Toolkit#144]
I hope this goes here.

The BHOM components in some of the SAM dynamo scripts I have been using are now marked as depreciated. FIne. I Tried installing **2.3.alpha.43** from the auto-created [sharepoint folder](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F13%5FInstallers%2FBHoM%20Installer%20%2D%20Auto%20Created) - there are two later versions but the folders are empty- but the BHOM components in my dynamo file are still depreciated. Is this the correct place to download the latest installer? I tried the link in the wiki but got a 404 error.

![image](https://user-images.githubusercontent.com/43270303/60087700-d2fb6200-973d-11e9-89eb-e5bbfe581b05.png)

It would be great if the error messages also contained information about how to get the latest version of these components.

**Comment by michaldengusiak** [comment]
@JustinZarbBH 
today new version of BHoM was merged, I will update all scripts to latest version

**Comment by adecler** [comment]
@michaldengusiak , can this issue be closed ?
