### ISSUE TITLE
Dynamo_Toolkit: global menu does not work in DynamoRevit

### ISSUE THREAD

**Issue by epignatelli** [BHoM/Dynamo_Toolkit#146]
But only in the DynamoSandbox version

**Comment by ZiolkowskiJakub** [comment]
SerachMenu keyboard control ctrl+shift+b does not work when Dynamo run directly from Revit. It works fine in sandbox mode.

**Comment by epignatelli** [comment]
Closing as duplicate of #147

**Comment by epignatelli** [comment]
Ok, that's getting weird - both closed, I'll reopen this.
