### ISSUE TITLE
Dynamo_Toolkit: Conflict with library prevent from loading BHoM into Dynamo Sandbox

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Dynamo_Toolkit#159]
#### Description:

My current BuildingEnvironmnet set of tools see details in test file folder,  prohibit BHoM from from loading into DynamoSandbox

#### How to replicate:

Build repos and open DynamoSandbox

#### Expected behaviour:

when opening Dynamo Sandbox it should load BHoM

#### Test file(s):

[test file with details](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Dynamo_Toolkit/Dynamo_Toolkit-Issue159-library?csf=1&e=J0kZVf)

**Comment by michaldengusiak** [comment]
ok it took a quite a long time to load one by one to find problem  but I identified issues...see powerpoint in `test file`

**Comment by FraserGreenroyd** [comment]
https://github.com/BHoM/Revit_Toolkit/pull/355 this PR may resolve this - can you give it a try with @ZiolkowskiJakub ?

**Comment by adecler** [comment]
It seems to be working for me.
@michaldengusiak , @ZiolkowskiJakub , can you confirm the PR mentioned by @FraserGreenroyd  is fixing the problem ?
