### ISSUE TITLE
UI: some components have unwanted minus buttons that can be harmful

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Dynamo_Toolkit#192]
#### Description:

After placing on canvas, some BHoM components have minus buttons that are active and can be clicked, which results in disappearance of the relevant input:

![minusOnInputs](https://user-images.githubusercontent.com/26874773/72158009-831e7880-33b9-11ea-8b58-7e1d2c8231e1.png)

#### Test file(s):

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FDynamo%5FToolkit%2FDynamo%5FToolkit%2DIssue192%2DMinusButtonsOnComponents).

**Comment by adecler** [comment]
@pawelbaran , this is not a bug, it's a feature.

We will soon be removing most of the create methods from the Engine. All the ones that simply map the method arguments to the properties of the objects without any computation feel like an unnecessary overhead for those creating BHoM objects.

This feature allow people to create BHoM objects by assigning the properties they care about and ignoring the other ones (i.e. leaving them to their default value).

![image](https://user-images.githubusercontent.com/16853390/72199972-72840600-347e-11ea-81eb-3bd45c58cb35.png)

**Comment by pawelbaran** [comment]
Thank you @adecler for clear explanation and sorry for digging further, but:
![InputBug](https://user-images.githubusercontent.com/26874773/72238659-aaa25a80-35de-11ea-913a-7dc9e59b8bc4.gif)

The wires should not be clicked into the 1st input on minus hit - they should disappear (opposite to GH, Dynamo does not allow more than one input wire on a single input).

**Comment by adecler** [comment]
@thanks @pawelbaran . Yes! that is definitely a bug that needs fixing.
