### ISSUE TITLE
Dynamo 1.3: wire gets clicked into first input after clicking minus on the component

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Dynamo_Toolkit#194]
#### Description:

Following discussion in #192:

![InputBug](https://user-images.githubusercontent.com/26874773/72238813-3ddb9000-35df-11ea-9f89-7e85d1a7722f.gif)

The wires should not be clicked into the 1st input on minus hit - they should disappear (opposite to GH, Dynamo does not allow more than one input wire on a single input).

Additionally, what gets left after deleting the component:
![image](https://user-images.githubusercontent.com/26874773/72238881-70858880-35df-11ea-89a0-b8d3f3a126ad.png)

**Comment by adecler** [comment]
This bug only happens in Dynamo 1.3, not in 2.0. I have changed the title to reflect that.
Given that 1.3 is not actively supported anymore, I have unassigned myself from this issue and lowered the priority to minor.
