### ISSUE TITLE
Geometry: Polyline conversion bug

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Dynamo_Toolkit#195]
#### Description:

Conversion of BHoM polyline -> Dynamo curve is missing:

![image](https://user-images.githubusercontent.com/26874773/72239680-1639f700-35e2-11ea-97a4-cf81bfc00f37.png)

Would be great to resolve it in 3.1 milestone as it is really annoying for the end users.

#### Test file(s):

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FDynamo%5FToolkit%2FDynamo%5FToolkit%2DIssue195%2DPolylineConversionBug).

**Comment by adecler** [comment]
It appears that this is not a bug but a missing feature. As you can see, your error is saying that hte method is not implemented and indeed: 

![image](https://user-images.githubusercontent.com/16853390/76484721-8edbf900-6455-11ea-8e52-b0941e78bdab.png)

Given that I know absolutely nothing about DesignScript and that the polycurve produced by dynamo actually stores its parts as `Curve` (not as the sub-classes), I don' see a way for me to fix this issue without learning what a Dynamo user probably already knows. So, it is better to have this issue handled by a Dynamo user.
