### ISSUE TITLE
Geometry: Bidirectional conversion of polylines

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Dynamo_Toolkit#196]
#### Description:
In opposition to BHoM, Dynamo does not support polylines as a distinct type: they are mere `Autodesk.DesignScript.Geometry.PolyCurves` with linear segments. As a consequence, all polylines get converted to `BH.oM.Geometry.PolyCurve`, which causes ambiguity and is very problematic while trying to build a BHoM workflow (where many features support only `BH.oM.Geometry.Polyline`).

I am wondering if it would not be better to force the convert to check if all segments of Dynamo polycurve are linear, and if so, then convert to `BH.oM.Geometry.Polyline` instead of `BH.oM.Geometry.PolyCurve`. A bit of an overhead, but BHoM <-> Dynamo geometry handling would become much more intuitive for the end user.

@al-fisher @rwemay what do you think?

**Comment by al-fisher** [comment]
> check if all segments of Dynamo polycurve are linear, and if so, then convert to BH.oM.Geometry.Polyline instead of BH.oM.Geometry.PolyCurve

Yes - agree with this approach. Good to put that overhead at convert to then simplify overall workflow as you say.
