### ISSUE TITLE
Dynamo_Toolkit does not work on Dynamo 2.3 under Revit 2020.2

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Dynamo_Toolkit#207]
#### Description:

As in the title: in Dynamo 2.3 on Revit 2020.2 empty BHoM method components do not change after picking the exact method, followed by the UI going crazy:

![DynamoBug](https://user-images.githubusercontent.com/26874773/74134991-c9027280-4beb-11ea-9da9-ad6f8e4c9829.gif)

Older versions of Revit and Dynamo seem to be not affected.

**Comment by enarhi** [comment]
Flagging as critical as this impedes any BHoM usage with R2020.

**Comment by enarhi** [comment]
@adecler any estimate of when we can tackle this? It is causing huge issues with ongoing Revit 2020 work.

**Comment by adecler** [comment]
@enarhi , I will have a look at it today. Sorry for leaving this stale for a while but I have far too many urgent things to deal with recently and with 2.3 not even being supported until recently, this was not considered as urgent as the rest.

**Comment by enarhi** [comment]
@adecler amazing, thanks. 

For all its worth, further testing show that BHoM still works in standalone Dynamo sandbox for v2.3 and v2.4.1. Not much use now that it is integrated into Revit separately though. 

I suspect it may have something to do with this from the 2.3 changelog:
"Dynamo will now prevent Packages that contain custom nodes from loading if you already have them loaded in another package. This can occur in situations where a Package contains custom nodes from another Package beyond itself. Specifically, you will no longer see the contents of one package overwrite the contents of another." Perhaps clashing dll's with the Revit_Toolkit dll dependencies?

**Comment by pawelbaran** [comment]
@enarhi @adecler we've just did some tests with @al-fisher and @IsakNaslundBh and found out that BHoM works fine for Dynamo 2.3.0 under Revit 2020 if one starts the work from placing a native component on canvas, and then jumps to any BHoM-related stuff (this also refers to loading already created files: to open a BHoM/Dynamo file, one first need to open an empty document, place a random native component, close the file and open the BHoM file).

The above suggests that the issue is related to the UI startup that gets triggered while placing the first component on canvas.

So it seems that for now we have a workaround @enarhi, I also hope the info will help with tracking the bug down.
