### ISSUE TITLE
Dynamo_Toolkit: components start from lacing shortest not auto

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Dynamo_Toolkit#228]
#### Description:

When a BHoM component gets dropped on a canvas, its lacing is by default set to _shortest_. This is nonintuitive as Dynamo default is _auto_ plus it is not the preferred setting for 99% cases.

![shortestVsAuto](https://user-images.githubusercontent.com/26874773/79741350-61f6ed80-8301-11ea-8499-3d18e1b20faf.png)

**Comment by pawelbaran** [comment]
@adecler do you have an idea where could that be set?

**Comment by adecler** [comment]
https://github.com/BHoM/Dynamo_Toolkit/search?q=lacing&unscoped_q=lacing
