### ISSUE TITLE
Dynamo_Toolkit: Push of a list happens item by item

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Dynamo_Toolkit#229]
#### Description:

When pushing a list of objects with BHoM `Push` each of them is packaged in a list and sent separately. This results in massive overhead + annoying UX issues.

#### Test file(s):

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FDynamo%5FToolkit%2FDynamo%5FToolkit%2DIssue229%2DPushlist) - open the _.dyn_ file and start an empty Revit model, push and see this under undo button (should be only one):

![image](https://user-images.githubusercontent.com/26874773/79742214-c6ff1300-8302-11ea-9dab-4fdbe390a57b.png)

**Comment by pawelbaran** [comment]
@adecler do you have an idea where could that be fixed?

**Comment by adecler** [comment]
Not sure I remember but this is a good place to start: https://github.com/BHoM/Dynamo_Toolkit/blob/cc54ddf17699075e542be01f506fa8480a824ac9/Dynamo20/Dynamo_UI/Templates/CallerComponent.cs#L217

**Comment by pawelbaran** [comment]
Seems that it works fine in Dynamo 2.X, so closing
