### ISSUE TITLE
Dynamo_Toolkit: shall we stop supporting Dynamo 1.3?

### ISSUE THREAD

**Issue by pawelbaran** [BHoM/Dynamo_Toolkit#249]
A few facts:
- Dynamo 2.0 is compatible with Revit since version 2017 and obligatory from 2020
- BHoM for Dynamo has not been updated for quite some time and contains a multitude of bugs
- we are aiming to migrate the assemblies to the central folder (https://github.com/BHoM/Dynamo_Toolkit/pull/240)

Facing all that, would it not be reasonable to shake off some burden and simply exclude Dynamo 1.3 from any future development, i.e. remove the projects, and exclude Dynamo 1.3 from the installer?

**Comment by pawelbaran** [comment]
On the other hand, it would be good to make sure that 2.1 and 2.2 are supported too.

**Comment by kayleighhoude** [comment]
@pawelbaran I know of quite a few users who continue to use 1.3.x versions for <2020 and only 2.1+ for >2020 per advice from Autodesk regarding 2.0

**Comment by pawelbaran** [comment]
Hmm, that is interesting. Do you know is there a valid reason behind using 1.3? I guess there is, curious what can it be :-)

Another question is whether these users do use BHoM.

**Comment by pawelbaran** [comment]
As discussed offline, we do not know any active BHoM+Dynamo1.3 users, therefore it should be a safe assumption that they do not exist ;-)

**Comment by rwemay** [comment]
Turning the question around slightly... if we removed support, how much work would it be to 'reinstate' if we find someone installs the latest beta and things break? If the answer is not too much, then maybe we push forward with this and add support if it's specifically needed. I do still use 1.3 quite a bit - opening up old scripts from the library that are useful, but I can't recall the last time I used BHoM+1.3, only Revit native applications.

**Comment by pawelbaran** [comment]
It should be possible to open 1.X Dynamo/BHoM scripts in 2.X (not the other way around) - I have just created the script below in 1.3.4, then opened successfully in 2.0 and 2.3.

![image](https://user-images.githubusercontent.com/26874773/90397911-dca9fc80-e098-11ea-9ca2-b2acd78cf0c8.png)

Following the above, I would say the worst case scenario seems to be the need to update the script from 1.X to 2.X. Alternatively, one could install an older version of BHoM. Would that convince you @rwemay?

**Comment by adecler** [comment]
> Would that convince you @rwemay?

That would convince me, at least 😄 

@rwemay, the problem with keeping 1.3 is that we are keeping a buggy and clunky version that will still require some work to compile after changes on BHoM_UI but will not be upgraded otherwise. So I feel this is a lose-lose situation where users have a worse version of the BHoM plugin and the developers still have work to do around it. Personally, as long as we can open old scripts in 2.X, I am happy. But again, I am not using Dynamo,
