### ISSUE TITLE
Dynamo 2.3.0.5885 crashing with BHoM 4.0.alpha (Revit 2020)

### ISSUE THREAD

**Issue by mikolaj-nazarczuk** [BHoM/Dynamo_Toolkit#280]
#### Description:
When i'm trying to run Dynamo 2.3.0.5885 in Revit 2020, at the first try there is dynamo crash.
![image](https://user-images.githubusercontent.com/75316519/102100703-08ac7300-3e2a-11eb-89d4-2d488e200a73.png)
Second try kills whole Revit

More info:
![image](https://user-images.githubusercontent.com/75316519/102101119-87a1ab80-3e2a-11eb-9d8e-7105b236d4f7.png)
![image](https://user-images.githubusercontent.com/75316519/102101153-8e302300-3e2a-11eb-8e54-ef93f35813f4.png)

after uninstalling:
![image](https://user-images.githubusercontent.com/75316519/102101249-a86a0100-3e2a-11eb-9da4-b4a4876a455d.png)

#### Steps to reproduce:
Install BHoM daily update
Run Revit 2020
Run dynamo (it's ok), new script (crash)

**Comment by adecler** [comment]
Works fine for me

![image](https://user-images.githubusercontent.com/16853390/102173246-8ed1c380-3ed5-11eb-9812-81ce4d54c370.png)


@pawelbaran , do you mind having a look ?

**Comment by pawelbaran** [comment]
Yeah I had a look and it works fine for me too. Also we tried to reinstall BHoM together with @mikolaj-nazarczuk on his machine, no success :< I could not come up with any explanation for this failure, therefore an issue has been raised.

**Comment by mikolaj-nazarczuk** [comment]
If it's an individual problem, I can handle it. I have plans to reinstall the system because I need a new hard drive. I'll let you know after that.

**Comment by arturtomczak** [comment]
You're not alone. I have the same issue on two separate machines. BHoM daily alpha from 26th Nov 2020. I had to uninstall bhom to be able to open Dynamo.

**Comment by pawelbaran** [comment]
I have just tested on today's Alpha, all works fine. I am wondering what could be a common denominator here?

**Comment by arturtomczak** [comment]
do we have some clean test environments? Mikołaj's env is quite fresh. Perhaps we could test on new windows user?

**Comment by pawelbaran** [comment]
I would wait with testing on more builds for now: as discussed with @mikolaj-nazarczuk, we will try to debug it on his machine at some point to see what goes wrong - hopefully that will give a proper hint to @adecler, so that we could fix it without having more machines/people involved.
