### ISSUE TITLE
Dynamo_Toolkit: Dynamo SAM scripts

### ISSUE THREAD

**Issue by michaldengusiak** [BHoM/Dynamo_Toolkit#43]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by adecler** [comment]
@michaldengusiak , is this still relevant ?

**Comment by michaldengusiak** [comment]
reviewed example and all this is completely changed now, so irrelevant...
