### ISSUE TITLE
Dynamo_Toolkit: Input, Output and Description for Nodes

### ISSUE THREAD

**Issue by ZiolkowskiJakub** [BHoM/Dynamo_Toolkit#91]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by michaldengusiak** [comment]
@ZiolkowskiJakub  as we discussed
reflection engine does not work in Dynamo 
Description, Input , Output is not displayed 

![image](https://user-images.githubusercontent.com/26113670/52020180-4038fd00-24e8-11e9-8267-ccd5aaf2ee65.png)

**Comment by michaldengusiak** [comment]
works fine now
![image](https://user-images.githubusercontent.com/26113670/61450123-4f085480-a94e-11e9-9f2b-d64f3fc5cad8.png)
